/**
 * Opt-in extension pack: **Wikibase** (`meta=wikibase`, `prop=pageterms`, `prop=wbentityusage`, `list=wblistentityusage`).
 *
 * Not in the default export: importing anything from this file — even just
 * the parameter interface you are about to use — activates the registry
 * augmentation at the bottom, which merges the modules into the request
 * gating automatically (no manual `declare module`):
 *
 * ```ts
 * import type {} from "types-mediawiki-params/ext/wikibase";
 * ```
 *
 * @see https://www.mediawiki.org/wiki/Extension:Wikibase
 */

import type { ApiLimit, OneOrMore } from "../common";

/**
 * Request parameters for the `meta=wikibase` query module provided by the extension.
 *
 * Get information about the Wikibase client and the associated Wikibase repository.
 */
export interface ApiQueryWikibaseParams {
  /**
   * Which properties to get
   */
  wbprop?: OneOrMore<"siteid" | "url">;
}
/**
 * Request parameters for the `prop=pageterms` query module provided by the extension.
 *
 * Get the Wikidata terms (typically labels, descriptions and aliases) associated with a page via a sitelink.
 */
export interface ApiQueryPagetermsParams {
  /**
   * When more results are available, use this to continue. More detailed information on how to continue queries can be found on mediawiki.org.
   */
  wbptcontinue?: number;
  /**
   * The language code to get terms in. If not specified, the user language is used.
   */
  wbptlanguage?:
    | "aa"
    | "aae"
    | "ab"
    | "abr"
    | "abs"
    | "ace"
    | "acf"
    | "acm"
    | "ady"
    | "ady-cyrl"
    | "aeb"
    | "aeb-arab"
    | "aeb-latn"
    | "af"
    | "agq"
    | "aig"
    | "ak"
    | "aln"
    | "als"
    | "alt"
    | "am"
    | "ami"
    | "an"
    | "ang"
    | "ann"
    | "anp"
    | "apc"
    | "ar"
    | "arc"
    | "arn"
    | "arq"
    | "ary"
    | "arz"
    | "as"
    | "ase"
    | "ast"
    | "atj"
    | "av"
    | "avk"
    | "awa"
    | "ay"
    | "az"
    | "azb"
    | "ba"
    | "bag"
    | "ban"
    | "ban-bali"
    | "bar"
    | "bas"
    | "bat-smg"
    | "bax"
    | "bbc"
    | "bbc-latn"
    | "bbj"
    | "bcc"
    | "bci"
    | "bcl"
    | "bdr"
    | "be"
    | "be-tarask"
    | "be-x-old"
    | "bew"
    | "bfd"
    | "bfw"
    | "bg"
    | "bgc"
    | "bgn"
    | "bh"
    | "bho"
    | "bi"
    | "bjn"
    | "bkc"
    | "bkh"
    | "bkm"
    | "blk"
    | "bm"
    | "bn"
    | "bo"
    | "bol"
    | "bpy"
    | "bqi"
    | "bqz"
    | "br"
    | "brh"
    | "bs"
    | "btm"
    | "bto"
    | "bug"
    | "bug-bugi"
    | "bxr"
    | "byv"
    | "ca"
    | "cak"
    | "cal"
    | "cbk-zam"
    | "ccp"
    | "cdo"
    | "cdo-hant"
    | "cdo-latn"
    | "ce"
    | "ceb"
    | "ch"
    | "chn"
    | "cho"
    | "chr"
    | "chy"
    | "ckb"
    | "cnh"
    | "co"
    | "cop"
    | "cps"
    | "cpx"
    | "cpx-hans"
    | "cpx-hant"
    | "cpx-latn"
    | "cr"
    | "crh"
    | "crh-cyrl"
    | "crh-latn"
    | "crh-ro"
    | "cs"
    | "csb"
    | "cu"
    | "cv"
    | "cy"
    | "da"
    | "dag"
    | "de"
    | "de-at"
    | "de-ch"
    | "de-formal"
    | "dga"
    | "din"
    | "diq"
    | "dlg"
    | "dsb"
    | "dso"
    | "dtp"
    | "dty"
    | "dua"
    | "dv"
    | "dz"
    | "ee"
    | "efi"
    | "egl"
    | "el"
    | "eml"
    | "en"
    | "en-ca"
    | "en-gb"
    | "en-us"
    | "eo"
    | "es"
    | "es-419"
    | "es-formal"
    | "et"
    | "eto"
    | "etu"
    | "eu"
    | "ewo"
    | "ext"
    | "fa"
    | "fat"
    | "ff"
    | "fi"
    | "fit"
    | "fiu-vro"
    | "fj"
    | "fkv"
    | "fmp"
    | "fo"
    | "fon"
    | "fr"
    | "frc"
    | "frp"
    | "frr"
    | "frs"
    | "fur"
    | "fvr"
    | "fy"
    | "ga"
    | "gaa"
    | "gag"
    | "gan"
    | "gan-hans"
    | "gan-hant"
    | "gcf"
    | "gcr"
    | "gd"
    | "gju-arab"
    | "gju-deva"
    | "gl"
    | "gld"
    | "glk"
    | "gn"
    | "gom"
    | "gom-deva"
    | "gom-latn"
    | "gor"
    | "got"
    | "gpe"
    | "grc"
    | "gsw"
    | "gu"
    | "guc"
    | "gur"
    | "guw"
    | "gv"
    | "gya"
    | "ha"
    | "hak"
    | "hak-hans"
    | "hak-hant"
    | "hak-latn"
    | "haw"
    | "he"
    | "hi"
    | "hif"
    | "hif-latn"
    | "hil"
    | "hke"
    | "hno"
    | "ho"
    | "hoc"
    | "hoc-latn"
    | "hr"
    | "hrx"
    | "hsb"
    | "hsn"
    | "ht"
    | "hu"
    | "hu-formal"
    | "hy"
    | "hyw"
    | "hz"
    | "ia"
    | "iba"
    | "ibb"
    | "id"
    | "ie"
    | "ig"
    | "igl"
    | "ii"
    | "ik"
    | "ike-cans"
    | "ike-latn"
    | "ilo"
    | "inh"
    | "io"
    | "is"
    | "isu"
    | "isv"
    | "isv-cyrl"
    | "isv-latn"
    | "it"
    | "iu"
    | "ja"
    | "jam"
    | "jbo"
    | "jut"
    | "jv"
    | "jv-java"
    | "ka"
    | "kaa"
    | "kab"
    | "kai"
    | "kaj"
    | "kbd"
    | "kbd-cyrl"
    | "kbp"
    | "kcg"
    | "kea"
    | "ker"
    | "kg"
    | "kge"
    | "kgg"
    | "khw"
    | "ki"
    | "kiu"
    | "kj"
    | "kjh"
    | "kjp"
    | "kk"
    | "kk-arab"
    | "kk-cn"
    | "kk-cyrl"
    | "kk-kz"
    | "kk-latn"
    | "kk-tr"
    | "kl"
    | "km"
    | "kn"
    | "knc"
    | "ko"
    | "ko-kp"
    | "koi"
    | "kr"
    | "krc"
    | "kri"
    | "krj"
    | "krl"
    | "ks"
    | "ks-arab"
    | "ks-deva"
    | "ksf"
    | "ksh"
    | "ksw"
    | "ku"
    | "ku-arab"
    | "ku-latn"
    | "kum"
    | "kus"
    | "kv"
    | "kw"
    | "ky"
    | "la"
    | "lad"
    | "lb"
    | "lbe"
    | "lem"
    | "lez"
    | "lfn"
    | "lg"
    | "li"
    | "lij"
    | "liv"
    | "ljp"
    | "lki"
    | "lkt"
    | "lld"
    | "lmo"
    | "ln"
    | "lns"
    | "lo"
    | "loz"
    | "lrc"
    | "lt"
    | "ltg"
    | "lua"
    | "lus"
    | "luz"
    | "lv"
    | "lzh"
    | "lzz"
    | "mad"
    | "mag"
    | "mai"
    | "map-bms"
    | "mcn"
    | "mcp"
    | "mdf"
    | "mg"
    | "mh"
    | "mhr"
    | "mi"
    | "min"
    | "mk"
    | "ml"
    | "mn"
    | "mnc"
    | "mnc-latn"
    | "mnc-mong"
    | "mni"
    | "mnw"
    | "mo"
    | "mos"
    | "mr"
    | "mrh"
    | "mrj"
    | "ms"
    | "ms-arab"
    | "mt"
    | "mua"
    | "mui"
    | "mul"
    | "mus"
    | "mwl"
    | "my"
    | "myv"
    | "mzn"
    | "na"
    | "nah"
    | "nan"
    | "nan-hani"
    | "nan-hant"
    | "nan-latn-pehoeji"
    | "nan-latn-tailo"
    | "nap"
    | "nb"
    | "nds"
    | "nds-nl"
    | "ne"
    | "new"
    | "ng"
    | "nge"
    | "nia"
    | "nit"
    | "niu"
    | "nl"
    | "nl-informal"
    | "nla"
    | "nmg"
    | "nmz"
    | "nn"
    | "nnh"
    | "nnz"
    | "no"
    | "nod"
    | "nog"
    | "nov"
    | "nqo"
    | "nr"
    | "nrm"
    | "nso"
    | "nup"
    | "nv"
    | "ny"
    | "nyn"
    | "nyo"
    | "nys"
    | "oc"
    | "ojb"
    | "olo"
    | "om"
    | "or"
    | "os"
    | "osa-latn"
    | "ota"
    | "pa"
    | "pag"
    | "pam"
    | "pap"
    | "pap-aw"
    | "pcd"
    | "pcm"
    | "pdc"
    | "pdt"
    | "pfl"
    | "pi"
    | "pih"
    | "pl"
    | "pms"
    | "pnb"
    | "pnt"
    | "ppl"
    | "prg"
    | "ps"
    | "pt"
    | "pt-br"
    | "pwn"
    | "qu"
    | "quc"
    | "qug"
    | "rgn"
    | "rif"
    | "rki"
    | "rm"
    | "rmc"
    | "rmf"
    | "rmy"
    | "rn"
    | "ro"
    | "roa-rup"
    | "roa-tara"
    | "rsk"
    | "ru"
    | "rue"
    | "rup"
    | "ruq"
    | "ruq-cyrl"
    | "ruq-latn"
    | "rut"
    | "rw"
    | "rwr"
    | "ryu"
    | "sa"
    | "sah"
    | "sas"
    | "sat"
    | "sc"
    | "scn"
    | "sco"
    | "sd"
    | "sdc"
    | "sdh"
    | "se"
    | "se-fi"
    | "se-no"
    | "se-se"
    | "sei"
    | "ses"
    | "sg"
    | "sgs"
    | "sh"
    | "sh-cyrl"
    | "sh-latn"
    | "shi"
    | "shi-latn"
    | "shi-tfng"
    | "shn"
    | "shy"
    | "shy-latn"
    | "si"
    | "simple"
    | "sjd"
    | "sje"
    | "sju"
    | "sk"
    | "skr"
    | "skr-arab"
    | "sl"
    | "sli"
    | "sm"
    | "sma"
    | "smj"
    | "smn"
    | "sms"
    | "sn"
    | "so"
    | "sq"
    | "sr"
    | "sr-ec"
    | "sr-el"
    | "srn"
    | "sro"
    | "srq"
    | "ss"
    | "st"
    | "stq"
    | "sty"
    | "su"
    | "sv"
    | "sva"
    | "sw"
    | "syl"
    | "szl"
    | "szy"
    | "ta"
    | "tay"
    | "tcy"
    | "tdd"
    | "te"
    | "tet"
    | "tg"
    | "tg-cyrl"
    | "tg-latn"
    | "th"
    | "thq"
    | "ti"
    | "tig"
    | "tk"
    | "tl"
    | "tly"
    | "tly-cyrl"
    | "tn"
    | "to"
    | "tok"
    | "tpi"
    | "tpv"
    | "tr"
    | "tru"
    | "trv"
    | "ts"
    | "tt"
    | "tt-cyrl"
    | "tt-latn"
    | "ttj"
    | "tum"
    | "tvu"
    | "tw"
    | "ty"
    | "tyv"
    | "tzm"
    | "udm"
    | "ug"
    | "ug-arab"
    | "ug-latn"
    | "uk"
    | "ur"
    | "uselang"
    | "uz"
    | "uz-cyrl"
    | "uz-latn"
    | "ve"
    | "vec"
    | "vep"
    | "vi"
    | "vls"
    | "vmf"
    | "vmw"
    | "vo"
    | "vot"
    | "vro"
    | "vut"
    | "wa"
    | "wal"
    | "war"
    | "wes"
    | "wls"
    | "wlx"
    | "wo"
    | "wuu"
    | "wuu-hans"
    | "wuu-hant"
    | "wya"
    | "xal"
    | "xh"
    | "xmf"
    | "xsy"
    | "yas"
    | "yat"
    | "yav"
    | "ybb"
    | "yi"
    | "yo"
    | "yrl"
    | "yua"
    | "yue"
    | "yue-hans"
    | "yue-hant"
    | "za"
    | "zea"
    | "zgh"
    | "zgh-latn"
    | "zh"
    | "zh-classical"
    | "zh-cn"
    | "zh-hans"
    | "zh-hant"
    | "zh-hk"
    | "zh-min-nan"
    | "zh-mo"
    | "zh-my"
    | "zh-sg"
    | "zh-tw"
    | "zh-yue"
    | "zu";
  /**
   * The types of terms to get, e.g. 'description', each returned as an array of strings keyed by their type, e.g. {"description": ["foo"]}. If not specified, all types are returned.
   */
  wbptterms?: OneOrMore<"alias" | "description" | "label">;
}
/**
 * Request parameters for the `prop=wbentityusage` query module provided by the extension.
 *
 * Returns all entity IDs used in the given pages.
 */
export interface ApiQueryWbentityusageParams {
  /**
   * Properties to add to the result.
   */
  wbeuprop?: OneOrMore<"url">;
  /**
   * Only return entity IDs that used this aspect.
   */
  wbeuaspect?: OneOrMore<"C" | "D" | "L" | "O" | "S" | "T" | "X">;
  /**
   * Only return page that used these entities.
   */
  wbeuentities?: OneOrMore<string>;
  /**
   * How many entity usages to return.
   */
  wbeulimit?: ApiLimit;
  /**
   * When more results are available, use this to continue. More detailed information on how to continue queries can be found on mediawiki.org.
   */
  wbeucontinue?: string;
}
/**
 * Request parameters for the `list=wblistentityusage` query module provided by the extension.
 *
 * Returns all pages that use the given entity IDs.
 */
export interface ApiQueryWblistentityusageParams {
  /**
   * Properties to add to the result.
   */
  wbleuprop?: OneOrMore<"url">;
  /**
   * Only return entity IDs that used this aspect.
   */
  wbleuaspect?: OneOrMore<"C" | "D" | "L" | "O" | "S" | "T" | "X">;
  /**
   * Entities that have been used.
   */
  wbleuentities: OneOrMore<string>;
  /**
   * How many entity usages to return.
   */
  wbleulimit?: ApiLimit;
  /**
   * When more results are available, use this to continue. More detailed information on how to continue queries can be found on mediawiki.org.
   */
  wbleucontinue?: string;
}

declare module "../registry" {
  interface QueryMetaParams {
    wikibase: ApiQueryWikibaseParams;
  }
  interface QueryPropParams {
    pageterms: ApiQueryPagetermsParams;
    wbentityusage: ApiQueryWbentityusageParams;
  }
  interface QueryListParams {
    wblistentityusage: ApiQueryWblistentityusageParams;
  }
  interface QueryGeneratorParams {
    wblistentityusage: ApiQueryWblistentityusageParams;
  }
}
